
clone: 
  git:
    image: woodpeckerci/plugin-git

pipeline:

  orchestrate:
    image: docker.ci.interactive-instruments.de/cicd/drone-docker-buildx
    privileged: true
    settings:
      registry: docker.ci.interactive-instruments.de
      repo: docker.ci.interactive-instruments.de/wau/orchestrate
      tags: latest
      force_tag: true
      pull_image: true
      platforms:
        - linux/amd64

  rest-api:
    image: docker.ci.interactive-instruments.de/cicd/drone-docker-buildx
    privileged: true
    settings:
      registry: docker.ci.interactive-instruments.de
      repo: docker.ci.interactive-instruments.de/wau/rest-api
      context: WaU-UC2/products/gebouw-rest-api
      tags: latest
      force_tag: true
      pull_image: true
      platforms:
        - linux/amd64

